// Founder review page for 026 topic groups: every proposed door with its
// words, what moved in, what sits behind two doors, and where each old
// group went. Writes public/preview-groups.html (a local preview, not
// committed — same as preview-core60.html).
//
//   node scripts/catalog/preview_topic_groups.mjs
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { seedResolver } from './seed_members.mjs';

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const read = (p) => JSON.parse(readFileSync(path.join(REPO, p), 'utf8'));
const LEX = read('data/launch_lexicon.json').entries;
const CAT = read('data/catalog/catalog.json');
const TODAY = read('data/group_seed.json');
const TOPICS = read('data/group_seed.topics.json');
const OUT = path.join(REPO, 'public/preview-groups.html');

const { members, doorsOn, home } = seedResolver(LEX, CAT);
const label = new Map(CAT.labels.filter((l) => l.kind === 'lemma' && l.locale === 'en').map((l) => [l.sense_id, l.text]));
const sense = new Map(CAT.senses.map((s) => [s.id, s]));
const name = (seed, key) => seed.groups.find((g) => g.key === key)?.names.en ?? key;

// D8: things and places take the neutral frame; people and pronouns stay yellow.
const PEOPLE = new Set(['People, Family & Roles', 'Function Words & Grammar', null]);
const role = (s) => {
  const x = sense.get(s);
  return x.fitzgerald_role === 'Yellow' && !PEOPLE.has(x.category) ? 'None' : x.fitzgerald_role;
};
const BANDS = [['None', 'Things'], ['Yellow', 'People'], ['Green', 'Actions'], ['Pink', 'Social & small words'],
  ['Blue', 'Describing'], ['Purple', 'Questions'], ['Red', 'Safety']];

const before = doorsOn(TODAY, 'grid60');
const after = doorsOn(TOPICS, 'grid60');
const unreachableToday = LEX.map((e) => `sns_${String(e.slot).padStart(4, '0')}`)
  .filter((s) => !home.grid60.has(s) && !before.has(s));

const esc = (t) => String(t).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;');
const icon = (key) => {
  const f = path.join(REPO, 'public/icons/groups', `${key}.svg`);
  if (!existsSync(f)) return null;
  return readFileSync(f, 'utf8').replace(/width="96" height="96"/, 'width="30" height="30"');
};

let changed = 0;
const cards = TOPICS.groups.filter((g) => g.key !== 'my_words').map((g) => {
  const ms = members(g);
  const chips = (band) => ms.filter((s) => role(s) === band).map((s) => {
    const was = [...(before.get(s) ?? [])];
    const now = [...(after.get(s) ?? [])].filter((k) => k !== g.key);
    const moved = !was.includes(g.key);
    if (moved) changed++;
    const from = was.length ? `was in ${was.map((k) => name(TODAY, k)).join(', ')}`
      : home.grid60.has(s) ? 'home-board word, repeated here' : 'was in no door on grid60';
    const tip = [from, now.length ? `also in ${now.map((k) => name(TOPICS, k)).join(', ')}` : ''].filter(Boolean).join(' · ');
    return `<span class="chip r-${role(s)}${moved ? ' moved' : ''}" title="${esc(tip)}">${esc(label.get(s))}${now.length ? '<sup>2</sup>' : ''}</span>`;
  }).join('');
  const bands = BANDS.map(([b, t]) => {
    const c = chips(b);
    return c ? `<div class="band"><span class="bname">${t}</span>${c}</div>` : '';
  }).join('');
  const glyph = icon(g.key) ?? `<span class="emoji">${g.glyph ?? ''}</span>`;
  const only = g.layouts ? `<span class="only">${g.layouts.join(', ')} only</span>` : '';
  const pctFull = Math.min(100, Math.round((100 * ms.length) / 57));
  return `<section class="door${g.layouts ? ' limited' : ''}">
    <header><span class="gl">${glyph}</span><h2>${esc(g.names.en)}</h2>${only}
      <span class="count">${ms.length}<small>/57</small></span></header>
    <div class="meter"><i style="width:${pctFull}%"></i></div>
    ${bands}
  </section>`;
}).join('');

const oldRows = TODAY.groups.filter((g) => g.key !== 'my_words').map((g) => {
  const to = new Map();
  for (const s of members(g)) for (const k of after.get(s) ?? ['(home board only)']) to.set(k, (to.get(k) ?? 0) + 1);
  const cells = [...to].sort((a, b) => b[1] - a[1]).map(([k, n]) => `${esc(name(TOPICS, k))} <b>${n}</b>`).join(' · ');
  return `<tr><td>${esc(g.names.en)}</td><td>${cells}</td></tr>`;
}).join('');

const doors = TOPICS.groups.filter((g) => g.key !== 'my_words');
const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Topic Groups Review</title>
<!-- Local founder review (026). Generated by scripts/catalog/preview_topic_groups.mjs — not committed. -->
<style>
  @font-face { font-family: "Andika"; src: url("/fonts/andika-bold.woff2") format("woff2"); font-weight: 700; }
  :root { --ink: #1a1a1a; --muted: #5b5348; --line: #d8d4c8; --cream: #f6f4ef; --tray: #e8e3d6;
    --word-font: "Andika", -apple-system, "Helvetica Neue", sans-serif; }
  .r-Yellow { --rb: #b07f00; --rf: #fdf0c8; } .r-Green { --rb: #2e8b3a; --rf: #dcf0dd; }
  .r-Blue { --rb: #2f6fd0; --rf: #dcecfd; } .r-Pink { --rb: #d0438c; --rf: #fbdfee; }
  .r-Purple { --rb: #6f55b0; --rf: #ebe5f7; } .r-Red { --rb: #c62828; --rf: #fbdcdc; }
  .r-None { --rb: #8a8578; --rf: #f2efe6; }
  * { box-sizing: border-box; margin: 0; }
  body { font-family: -apple-system, "Helvetica Neue", sans-serif; background: var(--cream); color: var(--ink); padding: 20px 16px 60px; }
  main { max-width: 1240px; margin: 0 auto; }
  h1 { font-size: 22px; } .lede { color: var(--muted); font-size: 14px; line-height: 1.5; max-width: 900px; margin: 6px 0 14px; }
  .stats { display: flex; flex-wrap: wrap; gap: 10px; margin-bottom: 14px; }
  .stat { background: #fff; border: 1px solid var(--line); border-radius: 10px; padding: 10px 14px; }
  .stat b { font-size: 22px; display: block; } .stat span { font-size: 12px; color: var(--muted); }
  .controls { display: flex; gap: 8px; align-items: center; flex-wrap: wrap; margin-bottom: 16px; font-size: 13px; color: var(--muted); }
  .controls button { font: inherit; font-size: 14px; padding: 6px 12px; border: 2px solid #8a8578; background: #fff; border-radius: 8px; cursor: pointer; color: var(--ink); }
  .controls button[aria-pressed="true"] { background: var(--ink); color: #fff; border-color: var(--ink); }
  .legend { display: flex; gap: 12px; flex-wrap: wrap; font-size: 13px; color: var(--muted); }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(360px, 1fr)); gap: 14px; }
  .door { background: #fff; border: 1px solid var(--line); border-radius: 14px; padding: 12px 14px; }
  .door.limited { border-style: dashed; }
  .door header { display: flex; align-items: center; gap: 10px; }
  .door h2 { font-size: 17px; flex: 1; }
  .gl { width: 30px; height: 30px; display: flex; align-items: center; justify-content: center; }
  .emoji { font-size: 22px; opacity: .55; }
  .only { font-size: 11px; background: var(--tray); border-radius: 6px; padding: 2px 6px; color: var(--muted); }
  .count { font-weight: 700; font-size: 18px; } .count small { color: var(--muted); font-weight: 400; font-size: 12px; }
  .meter { height: 4px; background: var(--tray); border-radius: 2px; margin: 8px 0 10px; overflow: hidden; }
  .meter i { display: block; height: 100%; background: #8a8578; }
  .band { display: flex; flex-wrap: wrap; gap: 4px; align-items: center; margin-bottom: 6px; }
  .bname { font-size: 11px; color: var(--muted); width: 74px; flex: none; }
  .chip { font-family: var(--word-font); font-weight: 700; font-size: 13px; padding: 2px 7px; border-radius: 6px;
    background: var(--rf); border: 2px solid var(--rb); line-height: 1.3; cursor: default; }
  .chip.moved { box-shadow: 0 0 0 2px #fff, 0 0 0 4px var(--ink); }
  .chip sup { font-size: 9px; margin-left: 1px; }
  body.changed-only .chip:not(.moved) { opacity: .18; }
  .panel { background: #fff; border: 1px solid var(--line); border-radius: 14px; padding: 14px 16px; margin-top: 22px; }
  .panel h2 { font-size: 16px; margin-bottom: 8px; }
  table { border-collapse: collapse; width: 100%; font-size: 13px; } td { border-top: 1px solid var(--line); padding: 6px 8px; vertical-align: top; }
  td:first-child { font-weight: 700; white-space: nowrap; width: 130px; }
  .panel p { font-size: 13px; color: var(--muted); line-height: 1.5; }
  @media (max-width: 420px) { .grid { grid-template-columns: 1fr; } }
</style>
</head>
<body>
<main>
  <h1>Topic groups — mapping review</h1>
  <p class="lede">Each door holds a whole topic: things, actions, describing words. Words are colored as proposed (things neutral, people yellow). <b>Ringed</b> = moves into this door. <sup>2</sup> = also behind another door. Hover a word to see where it was. Dashed doors show on the 15-cell board only. Decisions: <code>docs/phases/026_Topic_Groups.md</code>; source: <code>data/group_seed.topics.json</code>.</p>
  <div class="stats">
    <div class="stat"><b>${doors.filter((g) => !g.layouts).length}</b><span>doors on grid60 (+${doors.filter((g) => g.layouts).length} on grid15)</span></div>
    <div class="stat"><b>${Math.max(...doors.map((g) => members(g).length))}</b><span>biggest door (one page = 57)</span></div>
    <div class="stat"><b>${[...after].filter(([, k]) => k.size > 1).length}</b><span>words behind two doors</span></div>
    <div class="stat"><b>${unreachableToday.length}</b><span>words no door reached on grid60 — now placed</span></div>
    <div class="stat"><b>10.6% → 14.8%</b><span>child lines with 2+ door words served by one door (CHILDES)</span></div>
  </div>
  <div class="controls">
    <button id="only" aria-pressed="false">Show only moved words</button>
    <div class="legend">${BANDS.map(([b, t]) => `<span class="chip r-${b}">${t}</span>`).join('')}</div>
  </div>
  <div class="grid">${cards}</div>
  <div class="panel"><h2>Where each old group went</h2><table>${oldRows}</table></div>
  <div class="panel"><h2>Newly reachable on grid60</h2>
    <p>${unreachableToday.map((s) => `<b>${esc(label.get(s))}</b> → ${[...(after.get(s) ?? [])].map((k) => esc(name(TOPICS, k))).join(', ')}`).join(' · ')}</p></div>
</main>
<script>
  document.getElementById('only').addEventListener('click', (e) => {
    const on = document.body.classList.toggle('changed-only');
    e.currentTarget.setAttribute('aria-pressed', String(on));
  });
</script>
</body>
</html>`;
writeFileSync(OUT, html);
console.log(`${path.relative(REPO, OUT)}: ${doors.length} doors, ${changed} word placements new to their door`);
