// Founder review page for the compiled group seed (027 A1). Reads only
// the catalog the build emits — the same membership and per-size
// positions the board installs — and draws every group page on every
// board size, with the reserved cells (top row, frame, Next) shown the
// way the board shows them: the top row and frame are the home board's.
//
// Writes public/preview-blocks.html (local preview, not committed).
//
//   node scripts/catalog/preview_blocks.mjs
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
import { groupGeometry } from '../../public/shared/groups.mjs';

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const read = (p) => JSON.parse(readFileSync(path.join(REPO, p), 'utf8'));
const CAT = read('data/catalog/catalog.json');
const OUT = path.join(REPO, 'public/preview-blocks.html');

const label = new Map(CAT.labels.filter((l) => l.kind === 'lemma' && l.locale === 'en').map((l) => [l.sense_id, l.text]));
const sense = new Map(CAT.senses.map((s) => [s.id, s]));
const imageKey = new Map(CAT.images.map((i) => [i.id, i.key]));
const groupName = new Map(CAT.groupLabels.filter((g) => g.locale === 'en').map((g) => [g.group_id, g.text]));
const SIZES = Object.keys(CAT.layouts).sort((a, b) =>
  CAT.layouts[a].cols * CAT.layouts[a].rows - CAT.layouts[b].cols * CAT.layouts[b].rows);

// One view per group page, top row on; the home board first. The page
// blanks the top-row cells when the setting is off — still reserved
// (027 B6).
function views(size) {
  const L = CAT.layouts[size];
  const geom = groupGeometry(L);
  const home = CAT.coreCells.filter((c) => c.layout === size);
  const homeGrid = Array(geom.cells).fill(null);
  for (const c of home) homeGrid[c.slot_index] = c.sense_id;
  const out = [{ key: 'home', name: 'Home board', grid: homeGrid }];
  for (const g of CAT.groups) {
    if (g.layouts && !g.layouts.includes(size)) continue;
    const cells = CAT.groupCells.filter((c) => c.group_id === g.id && c.layout === size);
    if (!cells.length) continue;
    const pages = Math.max(...cells.map((c) => c.page)) + 1;
    for (let p = 0; p < pages; p++) {
      const grid = Array(geom.cells).fill(null);
      for (const s of geom.frame) grid[s] = homeGrid[s];
      for (const s of geom.topRow) grid[s] = homeGrid[s];
      for (const c of cells) if (c.page === p) grid[c.slot_index] = c.item_id;
      out.push({ key: `${g.id}:${p}`, name: groupName.get(g.id) + (pages > 1 ? ` ${p + 1}/${pages}` : ''), grid });
    }
  }
  return out;
}

// ---- measure from the rendered grids ----
function measure(vs) {
  const cells = new Map();
  for (const v of vs.slice(1)) v.grid.forEach((s, c) => {
    if (!s) return;
    if (!cells.has(s)) cells.set(s, { n: 0, at: new Set() });
    cells.get(s).n++;
    cells.get(s).at.add(c);
  });
  const rep = [...cells.values()].filter((x) => x.n > 1);
  return { repeated: rep.length, same: rep.filter((x) => x.at.size === 1).length, cells };
}
const topRowOff = (vs, topRow) => vs.map((v, i) =>
  (i === 0 ? v : { ...v, grid: v.grid.map((s, c) => (topRow.includes(c) ? null : s)) }));
const sizes = Object.fromEntries(SIZES.map((size) => {
  const { topRow } = groupGeometry(CAT.layouts[size]);
  const on = views(size);
  const stats = { on: measure(on), off: measure(topRowOff(on, topRow)) };
  return [size, { cols: CAT.layouts[size].cols, topRow, views: on, stats }];
}));

// ---- art + roles ----
const allWords = new Set(Object.values(sizes).flatMap((z) => z.views.flatMap((v) => v.grid.filter(Boolean))));
const art = new Map();
for (const s of allWords) {
  const key = imageKey.get(sense.get(s)?.default_image_id);
  const f = key && path.join(REPO, 'public', key);
  if (!f || !existsSync(f)) continue;
  const buf = await sharp(f).resize(88, 88, { fit: 'contain', background: '#fff' }).webp({ quality: 60 }).toBuffer();
  art.set(s, `data:image/webp;base64,${buf.toString('base64')}`);
}
const words = Object.fromEntries([...allWords].map((s) => [s, { label: label.get(s), role: sense.get(s)?.fitzgerald_role, art: art.get(s) ?? null }]));
const data = {
  words,
  sizes: Object.fromEntries(Object.entries(sizes).map(([size, z]) => [size, {
    cols: z.cols,
    topRow: z.topRow,
    views: z.views,
    stats: Object.fromEntries(Object.entries(z.stats).map(([m, st]) => [m, { repeated: st.repeated, same: st.same }])),
  }])),
};
const svg = (f) => readFileSync(path.join(REPO, 'public/icons', f), 'utf8')
  .replace(/<metadata>[\s\S]*?<\/metadata>/, '').replace(/ xmlns:c2pa="[^"]*"/, '')
  .replace(/width="96" height="96"/, 'width="30" height="30"');

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Group Seed</title>
<!-- Local founder preview (027 A1). Generated by scripts/catalog/preview_blocks.mjs from data/catalog/catalog.json — not committed. -->
<style>
  @font-face { font-family: "Andika"; src: url("/fonts/andika-bold.woff2") format("woff2"); font-weight: 700; }
  :root { --ink: #2a241d; --ink-text: #1a1a1a; --cream: #f6f4ef; --line: #d8d4c8; --tray: #e8e3d6; --edge: #8a8578;
    --muted: #5b5348; --gap: 6px; --word-font: "Andika", -apple-system, "Helvetica Neue", sans-serif; }
  .r-Yellow { --rb: #b07f00; --rf: #fdf0c8; } .r-Green { --rb: #2e8b3a; --rf: #dcf0dd; }
  .r-Blue { --rb: #2f6fd0; --rf: #dcecfd; } .r-Pink { --rb: #d0438c; --rf: #fbdfee; }
  .r-Purple { --rb: #6f55b0; --rf: #ebe5f7; } .r-Red { --rb: #c62828; --rf: #fbdcdc; } .r-None { --rb: #8a8578; --rf: #f2efe6; }
  * { box-sizing: border-box; margin: 0; }
  body { font-family: -apple-system, "Helvetica Neue", sans-serif; background: var(--cream); color: var(--ink-text); padding: 16px; }
  main { max-width: 1180px; margin: 0 auto; }
  h1 { font-size: 21px; } .lede { color: var(--muted); font-size: 14px; line-height: 1.5; margin: 4px 0 12px; max-width: 920px; }
  .tabs { display: flex; gap: 6px; flex-wrap: wrap; margin-bottom: 10px; align-items: center; }
  .tabs button { font: inherit; font-size: 15px; padding: 7px 14px; border: 2px solid var(--edge); background: #fff; border-radius: 10px; cursor: pointer; }
  .tabs button[aria-pressed="true"] { background: var(--ink); color: #fff; border-color: var(--ink); }
  .tabs label { font-size: 13px; color: var(--muted); display: flex; gap: 6px; align-items: center; margin-left: 8px; }
  .device { background: #1d1a16; border-radius: 26px; padding: 12px; }
  .screen { background: var(--cream); border-radius: 16px; padding: 10px; }
  .topbar { display: grid; grid-template-columns: 56px 1fr; gap: 8px; margin-bottom: 8px; }
  .corner { display: flex; align-items: center; justify-content: center; border-radius: 12px; }
  .corner.back { border: 2px solid var(--ink); background: #fff; } .corner.gear { opacity: .6; }
  .bar { background: #fff; border: 2px solid var(--line); border-radius: 12px; min-height: 52px; display: flex; align-items: center; padding: 0 14px;
    font-family: var(--word-font); font-weight: 700; font-size: 20px; color: var(--muted); }
  .strip { display: flex; justify-content: flex-end; background: var(--tray); border-radius: 12px; padding: 6px; margin-bottom: 8px; }
  .strip .folder { width: 64px; height: 40px; border: 2px solid var(--edge); border-radius: 10px; display: flex; align-items: center; justify-content: center; }
  .gridwrap { position: relative; }
  .grid { display: grid; grid-template-columns: repeat(var(--cols), 1fr); gap: var(--gap); }
  .cell { aspect-ratio: 1.25; border-radius: 10px; border: 3px solid var(--rb); background: #fff; display: flex; flex-direction: column; overflow: hidden; min-width: 0; }
  .cell .tl { height: 26%; background: var(--rf); font-family: var(--word-font); font-weight: 700; font-size: clamp(9px, 1.25vw, 15px);
    display: flex; align-items: center; justify-content: center; white-space: nowrap; overflow: hidden; padding: 0 2px; }
  .cell .ta { flex: 1; min-height: 0; display: flex; align-items: center; justify-content: center; padding: 3px; }
  .cell .ta img { max-width: 100%; max-height: 100%; object-fit: contain; }
  .cell.hole { border: 0; background: transparent; }
  body.holes .cell.hole { border: 2px dashed var(--line); }
  .cell.same-as-last { outline: 3px solid #e8a200; outline-offset: 1px; }
  body:not(.ring) .cell.same-as-last { outline: none; }
  .row2 { display: grid; grid-template-columns: 1fr 300px; gap: 16px; margin-top: 16px; }
  .panel { background: #fff; border: 1px solid var(--line); border-radius: 14px; padding: 12px 14px; }
  .panel h2 { font-size: 15px; margin-bottom: 8px; } .panel p { font-size: 13px; line-height: 1.5; color: var(--muted); }
  .stat { font-size: 26px; font-weight: 700; }
  .minis { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; }
  .mini h3 { font-size: 12px; margin-bottom: 4px; }
  .mini .g { display: grid; grid-template-columns: repeat(var(--cols), 1fr); gap: 2px; }
  .mini .g i { aspect-ratio: 1.25; border-radius: 2px; background: var(--rf, transparent); border: 1px solid var(--rb, transparent); }
  .mini .g i.on { background: #e8a200; border-color: #e8a200; }
  @media (max-width: 860px) { .row2 { grid-template-columns: 1fr; } .minis { grid-template-columns: repeat(2, 1fr); } }
</style>
</head>
<body class="ring">
<main>
  <h1>Group seed — review</h1>
  <p class="lede">Every group page the build ships, on each board size. The top row and the frame (<b>yes, no, stop, help</b>) are the home board's cells, reserved on every page; the last cell is Next. Words repeated across Breakfast, Lunch, Dinner, Snack, Fruit and Drinks share one cell. Flip pages with the buttons or ← →. Amber ring = same word, same cell as the page you just left. Source: <code>data/group_seed.occasions.json</code>, <code>data/group_seed.topics.json</code>; decisions: <code>docs/phases/027_Occasion_Boards.md</code>.</p>
  <div class="tabs" id="sizes"></div>
  <div class="tabs" id="tabs"></div>
  <div class="tabs">
    <label><input type="checkbox" id="top" checked> Top row on every group</label>
    <label><input type="checkbox" id="hol"> Show empty cells</label>
    <label><input type="checkbox" id="rng" checked> Ring same-as-last</label>
  </div>
  <div class="device"><div class="screen">
    <div class="topbar"><div class="corner" id="corner"></div><div class="bar">I want …</div></div>
    <div class="strip"><div class="folder">${svg('folder.svg')}</div></div>
    <div class="gridwrap"><div class="grid" id="grid"></div></div>
  </div></div>
  <div class="row2">
    <div class="panel"><h2>Every page, one hover</h2><div class="minis" id="minis"></div></div>
    <div class="panel"><h2>Measured on the rendered pages</h2><div class="stat" id="stat"></div><p id="statp"></p></div>
  </div>
</main>
<script>
const D = ${JSON.stringify(data)};
const BACK = '<svg viewBox="0 0 24 24" width="30" height="30" fill="none" stroke="#2a241d" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M15 4.5 7.5 12l7.5 7.5"/></svg>';
const GEAR = ${JSON.stringify(svg('settings-gear.svg'))};
let size = 'grid60', mode = 'on', cur = 0, last = null;
const Z = () => D.sizes[size];
const V = () => (mode === 'on' ? Z().views
  : Z().views.map((v, i) => (i === 0 ? v : { ...v, grid: v.grid.map((s, c) => (Z().topRow.includes(c) ? null : s)) })));
const tabs = document.getElementById('tabs');
function tabsDraw() {
  tabs.innerHTML = '';
  V().forEach((v, i) => { const b = document.createElement('button'); b.textContent = v.name; b.onclick = () => show(i); tabs.appendChild(b); });
}
const sizesEl = document.getElementById('sizes');
Object.keys(D.sizes).forEach((z) => {
  const b = document.createElement('button');
  b.textContent = (D.sizes[z].views[0].grid.length) + ' cells';
  b.dataset.z = z;
  b.onclick = () => { size = z; cur = 0; last = null; sizesMark(); tabsDraw(); sizesMark(); tabsDraw(); minisDraw(); show(0, true); };
  sizesEl.appendChild(b);
});
const sizesMark = () => [...sizesEl.children].forEach((b) => b.setAttribute('aria-pressed', String(b.dataset.z === size)));
const flag = (id, cls) => { document.getElementById(id).onchange = (e) => document.body.classList.toggle(cls, e.target.checked); };
flag('hol', 'holes'); flag('rng', 'ring');
document.getElementById('top').onchange = (e) => { mode = e.target.checked ? 'on' : 'off'; last = null; show(cur, true); minisDraw(); };
function tile(s, c, prev) {
  const el = document.createElement('div');
  if (!s) { el.className = 'cell hole'; return el; }
  const w = D.words[s];
  el.className = 'cell r-' + w.role + (prev && prev[c] === s ? ' same-as-last' : '');
  el.innerHTML = '<span class="tl">' + w.label + '</span><span class="ta">' + (w.art ? '<img src="' + w.art + '" alt="">' : '') + '</span>';
  el.onmouseenter = () => light(s); el.onmouseleave = () => light(null);
  return el;
}
function show(i, keepLast) {
  if (!keepLast) last = V()[cur].grid;
  cur = i;
  const v = V()[i];
  [...tabs.querySelectorAll('button')].forEach((b, j) => b.setAttribute('aria-pressed', String(j === i)));
  const corner = document.getElementById('corner');
  corner.className = 'corner ' + (v.key === 'home' ? 'gear' : 'back');
  corner.innerHTML = v.key === 'home' ? GEAR : BACK;
  const g = document.getElementById('grid'); g.innerHTML = '';
  g.style.setProperty('--cols', Z().cols);
  v.grid.forEach((s, c) => g.appendChild(tile(s, c, last === v.grid ? null : last)));
  const st = Z().stats[mode];
  document.getElementById('stat').textContent = st.same + '/' + st.repeated;
  document.getElementById('statp').textContent = 'words on 2+ pages sit in the same cell on all of them. This page: ' + v.grid.filter(Boolean).length + ' of ' + v.grid.length + ' cells.';
}
const minis = document.getElementById('minis');
function minisDraw() {
  minis.innerHTML = '';
  V().forEach((v) => {
    const m = document.createElement('div'); m.className = 'mini'; m.innerHTML = '<h3>' + v.name + '</h3>';
    const g = document.createElement('div'); g.className = 'g'; g.style.setProperty('--cols', Z().cols);
    v.grid.forEach((s) => { const i = document.createElement('i'); if (s) { i.className = 'r-' + D.words[s].role; i.dataset.s = s; i.onmouseenter = () => light(s); i.onmouseleave = () => light(null); } g.appendChild(i); });
    m.appendChild(g); minis.appendChild(m);
  });
}
function light(s) { minis.querySelectorAll('i').forEach((i) => i.classList.toggle('on', !!s && i.dataset.s === s)); }
document.addEventListener('keydown', (e) => {
  if (e.target.tagName === 'INPUT') return;
  if (e.key === 'ArrowRight') show((cur + 1) % V().length);
  if (e.key === 'ArrowLeft') show((cur - 1 + V().length) % V().length);
});
sizesMark(); tabsDraw(); minisDraw(); show(0, true);
</script>
</body>
</html>`;
writeFileSync(OUT, html);
console.log(`${path.relative(REPO, OUT)} (${Math.round(html.length / 1024)} KB)`);
