#!/usr/bin/env node
/**
 * Build the iOS shared core + fixture harness bundles (phase 044 A0-S1).
 * Same --check idiom as catalog:build — the committed bundle is the
 * artifact; --check rebuilds in memory and diffs, so CI catches a stale
 * bundle after a shared-module edit.
 *
 *   node scripts/ios/build_core.mjs          writes the bundles
 *   node scripts/ios/build_core.mjs --check  read-only verify, exit 1 on drift
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "../..");
const check = process.argv.includes("--check");

const BANNER = `// GENERATED by scripts/ios/build_core.mjs — do not edit.
// Source: public/shared/ via scripts/ios/*.mjs. Rebuild: npm run ios:core.
// Runs under JavaScriptCore — no DOM, no fetch, no timers.
`;

const JOBS = [
  {
    entry: "scripts/ios/core_entry.mjs",
    out: "apps/PipAAC/PipAAC/Core/pip-core.js",
    globalName: "PIPCORE",
  },
  {
    entry: "scripts/ios/harness.mjs",
    out: "apps/PipAAC/PipAACTests/pip-harness.js",
    globalName: "PIPHARNESS",
  },
];

let failed = false;
for (const job of JOBS) {
  const result = await esbuild.build({
    absWorkingDir: repoRoot,
    entryPoints: [job.entry],
    bundle: true,
    format: "iife",
    globalName: job.globalName,
    platform: "neutral",
    target: "es2020", // JSC is well past this; keeps the output plain
    write: false,
    metafile: true,
  });
  const body = result.outputFiles[0].text;
  const outPath = join(repoRoot, job.out);
  const modules = Object.keys(result.metafile.inputs).sort();
  const header = `${BANNER}// Modules: ${modules.join(", ")}\n`;
  const text = header + body;
  if (check) {
    let existing = null;
    try { existing = readFileSync(outPath, "utf8"); } catch { /* missing */ }
    if (existing !== text) {
      console.error(`stale: ${job.out} — run npm run ios:core`);
      failed = true;
    }
  } else {
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, text);
    console.log(`wrote ${job.out} (${(text.length / 1024).toFixed(0)} KB, ${modules.length} modules)`);
  }
}
process.exit(failed ? 1 : 0);
