//
//  PipCore.swift
//  PipAAC
//
//  The shared rules engine: pip-core.js (generated by
//  scripts/ios/build_core.mjs from public/shared/) evaluated in one
//  JSContext on one serial queue — phase 044 A0-S1, the host side of
//  Platforms_iOS_And_Web § 2. JSContext is single-threaded; every entry
//  point funnels through `sync`/`enqueue`, never the caller's thread.
//

import Foundation
import JavaScriptCore
import os.log

public enum PipCoreError: Error, CustomStringConvertible {
    case bundleMissing(String)
    case evalFailed(String)
    public var description: String {
        switch self {
        case .bundleMissing(let n): return "bundle resource missing: \(n)"
        case .evalFailed(let m): return "js eval failed: \(m)"
        }
    }
}

/// Deliberately non-isolated + @unchecked Sendable: the class IS the
/// serialization story — every mutable touch happens on `queue`, and the
/// host blocks it hands JavaScriptCore only ever run there.
public nonisolated final class PipCore: @unchecked Sendable {
    private let queue = DispatchQueue(label: "org.pipaac.core", qos: .userInitiated)
    private let log = Logger(subsystem: "org.pipaac", category: "pipcore")
    private var ctx: JSContext?
    private var dbs: [Int32: PipDatabase] = [:]
    private var nextDbId: Int32 = 1

    public init() {}

    /// Runs `work` on the JS queue. Never call from inside the queue.
    @discardableResult
    public func sync<T>(_ work: () throws -> T) throws -> T {
        dispatchPrecondition(condition: .notOnQueue(queue))
        return try queue.sync(execute: work)
    }

    /// Async variant of sync() — the catch-up drain's "off the main
    /// actor" lane (phase 044 A0 pass list).
    public func enqueue(_ work: @escaping @Sendable () -> Void) {
        dispatchPrecondition(condition: .notOnQueue(queue))
        queue.async(execute: work)
    }

    // MARK: - Bundle + host (queue-only)

    /// Creates the JSContext if needed, installs __pipHost, evaluates a
    /// bundle resource. Call inside sync(). `bundle` is the resource's
    /// home: Bundle(for: PipCore.self) for app resources, the test
    /// bundle for pip-harness.js and fixtures.
    @discardableResult
    public func evaluate(resource: String, bundle: Bundle) throws -> JSContext {
        try ensureContext()
        guard let url = bundle.url(forResource: resource, withExtension: nil)
            ?? bundle.url(forResource: resource, withExtension: "js"),
            let src = try? String(contentsOf: url, encoding: .utf8)
        else { throw PipCoreError.bundleMissing(resource) }
        ctx!.evaluateScript(src)
        if let ex = ctx!.exception { throw PipCoreError.evalFailed(ex.toString() ?? "?") }
        return ctx!
    }

    /// Opens (or creates) a database file for the JS adapter to address
    /// by id. Queue-only.
    public func openDatabase(path: String) throws -> Int32 {
        let id = nextDbId
        nextDbId += 1
        dbs[id] = try PipDatabase(path: path)
        return id
    }
    public func closeDatabase(id: Int32) {
        dbs[id]?.close()
        dbs[id] = nil
    }

    /// `PIPCORE.f…` / `PIPHARNESS.f…` call. Returns the JSValue's
    /// Foundation value (String, NSNumber, [String: Any], …). Queue-only.
    @discardableResult
    public func call(_ object: String, _ method: String, _ args: [Any] = []) throws -> Any? {
        guard let ctx else { throw PipCoreError.evalFailed("no context") }
        guard let obj = ctx.objectForKeyedSubscript(object), obj.isObject,
              let fn = obj.objectForKeyedSubscript(method), fn.isObject else {
            throw PipCoreError.evalFailed("no \(object).\(method)")
        }
        let v = fn.call(withArguments: args)
        if let ex = ctx.exception {
            ctx.exception = nil
            throw PipCoreError.evalFailed(ex.toString() ?? "?")
        }
        return v?.toObject()
    }

    /// Same call but the raw JSValue — for passing one result into the
    /// next call (canon comparisons) without a Foundation round-trip.
    @discardableResult
    public func callValue(_ object: String, _ method: String, _ args: [Any] = []) throws -> JSValue {
        guard let ctx else { throw PipCoreError.evalFailed("no context") }
        guard let obj = ctx.objectForKeyedSubscript(object), obj.isObject,
              let fn = obj.objectForKeyedSubscript(method), fn.isObject else {
            throw PipCoreError.evalFailed("no \(object).\(method)")
        }
        let v = fn.call(withArguments: args)
        if let ex = ctx.exception {
            ctx.exception = nil
            throw PipCoreError.evalFailed(ex.toString() ?? "?")
        }
        return v ?? JSValue(undefinedIn: ctx)
    }

    // MARK: - __pipHost

    private func ensureContext() throws {
        if ctx != nil { return }
        let c = JSContext()!
        ctx = c
        c.exceptionHandler = { [weak self] _, ex in
            self?.log.error("JS exception: \(ex?.toString() ?? "?")")
        }
        let host = JSValue(newObjectIn: c)!

        // Database seam — the makeDb() side of the bridge expects exactly
        // these shapes (scripts/ios/core_entry.mjs).
        host.setValue({ [weak self] (idv: JSValue, sqlv: JSValue) -> Any? in
            self?.withDb(idv) { db in try db.exec(sqlv.toString()); return NSNull() }
        } as @convention(block) (JSValue, JSValue) -> Any?, forProperty: "dbExec")

        host.setValue({ [weak self] (idv: JSValue, sqlv: JSValue, paramsv: JSValue) -> Any? in
            self?.withDb(idv) { db in
                ["changes": try db.run(sqlv.toString(), params: paramsv.toArray() ?? [])]
            }
        } as @convention(block) (JSValue, JSValue, JSValue) -> Any?, forProperty: "dbRun")

        host.setValue({ [weak self] (idv: JSValue, sqlv: JSValue, paramsv: JSValue) -> Any? in
            self?.withDb(idv) { db in
                let r = try db.all(sqlv.toString(), params: paramsv.toArray() ?? [])
                return ["columns": r.columns, "rows": r.rows]
            }
        } as @convention(block) (JSValue, JSValue, JSValue) -> Any?, forProperty: "dbAll")

        // crypto.randomUUID — op/entity ids; uniqueness only.
        host.setValue({ () -> String in
            UUID().uuidString.lowercased()
        } as @convention(block) () -> String, forProperty: "randomUUID")

        // crypto.getRandomValues backing — never key material.
        host.setValue({ (nv: JSValue) -> [NSNumber] in
            let n = Int(nv.toInt32())
            var bytes = [UInt8](repeating: 0, count: n)
            _ = bytes.withUnsafeMutableBytes {
                SecRandomCopyBytes(kSecRandomDefault, n, $0.baseAddress!)
            }
            return bytes.map { NSNumber(value: $0) }
        } as @convention(block) (JSValue) -> [NSNumber], forProperty: "randomBytes")

        host.setValue({ [weak self] (level: JSValue, msg: JSValue) in
            self?.log.debug("[jsc:\(level.toString() ?? "log")] \(msg.toString() ?? "")")
        } as @convention(block) (JSValue, JSValue) -> Void, forProperty: "log")

        c.setObject(host, forKeyedSubscript: "__pipHost" as NSString)
    }

    private func withDb(_ idv: JSValue, _ body: (PipDatabase) throws -> Any) -> Any? {
        guard let db = dbs[idv.toInt32()] else {
            return ["__err": "unknown db \(idv.toInt32())"]
        }
        do { return try body(db) }
        catch { return ["__err": "\(error)"] }
    }
}
