#!/usr/bin/env node
/**
 * 036 § A — generate the service-worker precache manifest.
 *
 *   node scripts/sw/sw_manifest.mjs           # write outputs
 *   node scripts/sw/sw_manifest.mjs --check   # drift gate (check:fast)
 *
 * Outputs:
 *   public/sw-manifest.json — {buildId, files:[{path, bytes, sha256}]},
 *     the URL list public/sw.js precaches at install.
 *   public/sw-build.js     — `self.SW_BUILD = "<buildId>"`, importScripts'd
 *     by sw.js so each installed SW instance knows which versioned cache
 *     it owns (a manifest bump alone triggers the browser's SW update
 *     check, since importScripts resources are byte-compared).
 *
 * Everything under public/ is classified deliberately: a file that
 * lands outside PRECACHE_FILES / PRECACHE_DIRS / EXCLUDE fails the build
 * — a silently-unprecached boot dependency is exactly the lie this gate
 * exists to catch. `RELEASE` is the manual escape hatch for pinning a
 * fresh cache id without content changes (a killed release, 036 § 6).
 */
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { repoRoot } from "../catalog/paths.mjs";

const PUBLIC = join(repoRoot, "public");
const RELEASE = 1;

const PRECACHE_FILES = [
  "index.html",
  "board.js",
  "db.js",
  "catalog.json",
  "phrase_table.en.json",
  "feeling_voice.json",
  "manifest.webmanifest",
];
const PRECACHE_DIRS = [
  "audio",
  "board",
  "brand",
  "fonts",
  "icons",
  "shared",
  "symbols",
  "vendor",
];
/** Named exclusions — SW machinery and the raw .gz source the Worker
 *  route reads. */
const EXCLUDE_FILES = new Set([
  "_headers",
  "sw.js",
  "sw-build.js",
  "sw-manifest.json",
  "form_table.en.json.gz",
]);

const sha256 = (buf) => createHash("sha256").update(buf).digest("hex");

const walk = (dir, out) => {
  for (const name of readdirSync(join(PUBLIC, dir)).sort()) {
    if (name.startsWith(".")) continue;
    const rel = join(dir, name);
    const stat = statSync(join(PUBLIC, rel));
    if (stat.isDirectory()) walk(rel, out);
    else out.push(rel);
  }
};

const files = [];   // { path: "/x", bytes, sha256 }
const push = (rel, buf) =>
  files.push({ path: `/${rel.split("/").join("/")}`, bytes: buf.length, sha256: sha256(buf) });

const failures = [];
for (const entry of readdirSync(PUBLIC).sort()) {
  if (entry.startsWith(".")) continue;
  const stat = statSync(join(PUBLIC, entry));
  if (stat.isDirectory()) {
    if (!PRECACHE_DIRS.includes(entry)) {
      failures.push(`unclassified public/${entry}/ — add to PRECACHE_DIRS or name its exclusions`);
      continue;
    }
    const under = [];
    walk(entry, under);
    for (const rel of under.sort()) {
      push(rel, readFileSync(join(PUBLIC, rel)));
    }
  } else if (PRECACHE_FILES.includes(entry)) {
    push(entry, readFileSync(join(PUBLIC, entry)));
  } else if (entry === "form_table.en.json") {
    failures.push("unexpected real file public/form_table.en.json — the .gz + Worker route own that path");
  } else if (EXCLUDE_FILES.has(entry) || entry.endsWith(".html")) {
    continue; // preview/review/lab pages are dev tooling, not shell
  } else {
    failures.push(`unclassified public/${entry} — precache it or exclude it deliberately`);
  }
}

/* /form_table.en.json is served by the Worker from the .gz bytes — no
 * real file exists at that path. The SW fetches the route at install and
 * stores the decoded body (network fetch transparently gunzips; sw.js
 * strips the stale content-encoding header). The manifest entry's hash
 * is the .gz file's hash — the deterministic identity of the payload. */
{
  const gz = readFileSync(join(PUBLIC, "form_table.en.json.gz"));
  files.push({ path: "/form_table.en.json", bytes: gz.length, sha256: sha256(gz), via: "worker-gz" });
}
files.sort((a, b) => a.path.localeCompare(b.path));

const buildId = `r${RELEASE}-${sha256(
  Buffer.from(files.map((f) => `${f.sha256} ${f.path}`).join("\n")),
).slice(0, 12)}`;
const manifest = JSON.stringify({ buildId, files }, null, 2) + "\n";
const swBuild = `// Generated by scripts/sw/sw_manifest.mjs — do not edit.\nself.SW_BUILD = "${buildId}";\n`;

if (failures.length) {
  for (const f of failures) console.error(`sw-manifest: ${f}`);
  process.exit(1);
}

const readOr = (name) => {
  try { return readFileSync(join(PUBLIC, name), "utf8"); } catch { return null; }
};
const drift = [
  ["sw-manifest.json", manifest],
  ["sw-build.js", swBuild],
].filter(([name, want]) => readOr(name) !== want).map(([name]) => name);

const stats = `${files.length} files, ${(files.reduce((s, f) => s + f.bytes, 0) / 1048576).toFixed(1)} MB, build ${buildId}`;
if (process.argv.includes("--check")) {
  if (drift.length) {
    for (const name of drift) console.error(`sw-manifest: stale ${name} — run scripts/sw/sw_manifest.mjs`);
    process.exit(1);
  }
  console.log(`sw-manifest OK — ${stats}`);
} else {
  writeFileSync(join(PUBLIC, "sw-manifest.json"), manifest, "utf8");
  writeFileSync(join(PUBLIC, "sw-build.js"), swBuild, "utf8");
  console.log(`sw-manifest: ${stats}`);
}
