/** Build the small offline list and the on-demand group icon library. */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dirname, "../..");
const read = (path) => readFileSync(join(root, path), "utf8");
const source = JSON.parse(read("data/group-icons/curation.json"));
const check = process.argv.includes("--check");
const names = new Set();
const write = (path, text) => {
  if (check) {
    if (read(path) !== text) throw new Error(`group icons drift: ${path}`);
  } else {
    mkdirSync(join(root, path, ".."), { recursive: true });
    writeFileSync(join(root, path), text);
  }
};

for (const icon of [...source.base, ...source.extra]) {
  if (!/^[a-z0-9_]+$/.test(icon.name) || names.has(icon.name)) throw new Error(`bad icon: ${icon.name}`);
  if (!icon.label || !icon.category || !Array.isArray(icon.tags)) throw new Error(`incomplete icon: ${icon.name}`);
  names.add(icon.name);
}
for (const icon of source.base) read(`public/icons/groups/${icon.name}.svg`);

const icons = source.extra.map(({ source: upstream, ...icon }) => {
  if (!icon.name.startsWith("extra_") || !/^[a-z0-9-]+$/.test(upstream)) throw new Error(`bad extra: ${icon.name}`);
  const svg = read(`assets/group-icons/lucide/${upstream}.svg`)
    .replace(/<!--.*?-->/gs, "")
    .replace(/\sclass="[^"]*"/, "")
    .replace('stroke="currentColor"', 'stroke="#2a241d"')
    .replace(/\s+/g, " ").trim();
  if (!svg.startsWith("<svg ") || /<(?:script|foreignObject|image)\b|\bon\w+=|href=/i.test(svg)) {
    throw new Error(`unsafe SVG: ${upstream}`);
  }
  write(`public/group-icons/${icon.name}.svg`, `${svg}\n`);
  return { ...icon, svg };
});
write("public/group-icons/library.json", `${JSON.stringify({ version: source.version, icons })}\n`);
write("public/group-icons/LICENSE.txt", read("assets/group-icons/LUCIDE-LICENSE.txt"));
write("public/shared/group-icon-library.mjs", `// Generated by scripts/group-icons/build.mjs from data/group-icons/curation.json.\nexport const BASE_GROUP_ICONS = ${JSON.stringify(source.base, null, 2)};\n`);
console.log(`group icons: ${source.base.length} offline + ${icons.length} on demand${check ? " (verified)" : ""}`);
