// GENERATED by scripts/ios/build_core.mjs — do not edit.
// Source: public/shared/ via scripts/ios/*.mjs. Rebuild: npm run ios:core.
// Runs under JavaScriptCore — no DOM, no fetch, no timers.
// Modules: scripts/ios/harness.mjs
var PIPHARNESS = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // scripts/ios/harness.mjs
  var harness_exports = {};
  __export(harness_exports, {
    barGolden: () => barGolden,
    benchHost: () => benchHost,
    canon: () => canon,
    canonJson: () => canonJson,
    closeDb: () => closeDb,
    db: () => db,
    dumpSynced: () => dumpSynced,
    formGolden: () => formGolden,
    installPending: () => installPending,
    loadTables: () => loadTables,
    matchCanonJson: () => matchCanonJson,
    oneEdit: () => oneEdit,
    probeBegin: () => probeBegin,
    probeFinish: () => probeFinish,
    probeSentenceEnd: () => probeSentenceEnd,
    probeSentenceStart: () => probeSentenceStart,
    probeTap: () => probeTap,
    probeTapTimed: () => probeTapTimed,
    runDrain: () => runDrain,
    runReplay: () => runReplay
  });
  var PIP = () => globalThis.PIPCORE;
  function canon(v) {
    if (v === null || typeof v === "number" || typeof v === "string" || typeof v === "boolean") return JSON.stringify(v);
    if (v instanceof Uint8Array) return canon({ b: [...v] });
    if (Array.isArray(v)) return `[${v.map(canon).join(",")}]`;
    return `{${Object.keys(v).filter((k) => v[k] !== void 0).sort().map((k) => `${JSON.stringify(k)}:${canon(v[k])}`).join(",")}}`;
  }
  var adapters = /* @__PURE__ */ new Map();
  function db(id) {
    if (!adapters.has(id)) adapters.set(id, PIP().makeDb(id));
    return adapters.get(id);
  }
  function closeDb(id) {
    adapters.delete(id);
  }
  var parse = (x) => typeof x === "string" ? JSON.parse(x) : x;
  function canonJson(json) {
    return canon(parse(json));
  }
  function matchCanonJson(got, json) {
    return canon(got) === canon(parse(json));
  }
  function installPending(dbId, ops) {
    const d = db(dbId);
    const ins = d.prepare(
      "INSERT INTO sync_op (op_id, device_id, kind, args, created_at) VALUES (?, ?, ?, ?, ?)"
    );
    for (const op of ops) {
      PIP().ops.applyOp(d, op);
      ins.run(
        op.op_id,
        op.device_id ?? "dev_local",
        op.kind,
        typeof op.args === "string" ? op.args : JSON.stringify(op.args),
        op.created_at ?? 0
      );
    }
  }
  function dumpSynced(dbId) {
    const d = db(dbId);
    const out = {};
    for (const t of PIP().ops.SYNCED_TABLES) {
      out[t] = d.prepare(`SELECT * FROM ${t} ORDER BY rowid`).all().map(canon);
    }
    return out;
  }
  function runReplay(dbId, fixture) {
    const fx = parse(fixture);
    installPending(dbId, fx.localOps);
    PIP().ops.drainOps(db(dbId), fx.relay);
    const got = dumpSynced(dbId);
    const diffs = [];
    const tables = /* @__PURE__ */ new Set([...Object.keys(fx.expect ?? {}), ...Object.keys(got)]);
    for (const t of tables) {
      const e = fx.expect?.[t] ?? [], g = got[t] ?? [];
      if (e.length !== g.length || e.some((r, i) => r !== g[i])) {
        diffs.push({
          table: t,
          expectRows: e.length,
          gotRows: g.length,
          firstDiffAt: e.findIndex((r, i) => r !== g[i]),
          expectSample: e.filter((r) => !g.includes(r)).slice(0, 3),
          gotSample: g.filter((r) => !e.includes(r)).slice(0, 3)
        });
      }
    }
    return { ok: diffs.length === 0, diffs };
  }
  function runDrain(dbId, relay) {
    PIP().ops.drainOps(db(dbId), parse(relay));
    return dumpSynced(dbId);
  }
  var sessions = /* @__PURE__ */ new Map();
  var nextSid = 1;
  var pinUtc = () => {
    Date.prototype.getTimezoneOffset = () => 0;
  };
  function probeBegin(dbId, kidsTable, formTable) {
    pinUtc();
    const sid = `s${nextSid++}`;
    sessions.set(sid, {
      d: db(dbId),
      kids: parse(kidsTable),
      forms: parse(formTable),
      sentence: [],
      sentenceId: null,
      pos: 0
    });
    return sid;
  }
  function probeSentenceStart(sid, at) {
    const s = sessions.get(sid);
    s.sentence = [];
    s.pos = 0;
    s.sentenceId = PIP().funnel.openSentence(s.d, at);
  }
  function probeSentenceEnd(sid, at) {
    const s = sessions.get(sid);
    if (s.sentenceId != null) {
      PIP().funnel.closeSentence(s.d, s.sentenceId, at, "spoken");
      s.sentenceId = null;
    }
  }
  function posOfSense(d, senseId, locale) {
    return d.prepare(
      `SELECT part_of_speech AS p FROM label
     WHERE sense_id = ? AND kind = 'lemma' AND status = 'approved' AND locale = ?`
    ).all(senseId, locale)[0]?.p ?? null;
  }
  function appendAndLog(s, kind, id, text, at) {
    const { d, forms, sentence } = s;
    let item = { kind, id, text };
    let form = null;
    if (kind === "sense" && id) {
      form = PIP().forms.formFor(d, forms, sentence, id);
      item = {
        kind: "sense",
        id: form.senseId,
        text: form.text ?? text,
        labelId: form.labelId,
        fixed: form.merged,
        features: form.features
      };
    }
    sentence.push(item);
    const atIndex = sentence.length - 1;
    let repick = null;
    if (atIndex >= 1) {
      const prev = sentence[atIndex - 1], cur = sentence[atIndex];
      if (prev.kind === "entity" && cur?.kind === "sense" && cur.id && posOfSense(d, cur.id, s.locale ?? "en") === "Noun" && !prev.text.endsWith("'s")) {
        repick = { pos: atIndex - 1, text: `${prev.text}'s` };
        prev.text = repick.text;
      } else if (prev.kind === "sense" && prev.id && !prev.fixed) {
        const re = PIP().forms.formFor(d, forms, sentence.slice(0, atIndex - 1), prev.id, cur);
        if (re.text !== prev.text) {
          repick = {
            pos: atIndex - 1,
            text: re.text,
            labelId: re.labelId,
            features: re.features
          };
          prev.text = re.text;
          prev.labelId = re.labelId;
          prev.features = re.features;
          if (s.sentenceId != null) {
            const pos = sentence.slice(0, atIndex - 1).filter((it) => it.id).length;
            d.prepare(
              "UPDATE learner_event_log SET label_id = ? WHERE sentence_id = ? AND position = ?"
            ).run(re.labelId, s.sentenceId, pos);
          }
        }
      }
    }
    if (id) {
      if (s.sentenceId == null) {
        s.sentenceId = PIP().funnel.openSentence(s.d, at);
      }
      PIP().funnel.fillChosen?.(s.d, s.sentenceId, { kind, id: item.id ?? id, source: "grid" });
      PIP().funnel.logSelection(s.d, kind, item.id ?? id, at, {
        sentenceId: s.sentenceId,
        position: s.pos++,
        source: "grid",
        labelId: item.labelId ?? null,
        groupId: null
      });
    }
    return { item, form, repick };
  }
  function probeTap(sid, tap, at) {
    const s = sessions.get(sid);
    const { form, repick } = appendAndLog(s, tap.kind, tap.id, tap.text, at);
    const strip = PIP().funnel.stripCandidates(
      s.d,
      s.sentence,
      at,
      s.locale ?? "en",
      s.kids
    );
    return canon({ form, repick, strip });
  }
  function probeFinish(sid) {
    sessions.delete(sid);
  }
  function benchHost(dbId, n = 200) {
    const st = db(dbId).prepare("SELECT 1 AS x");
    const t0 = Date.now();
    for (let i = 0; i < n; i++) st.all();
    return Date.now() - t0;
  }
  function probeTapTimed(sid, tap, at) {
    const s = sessions.get(sid);
    const t0 = Date.now();
    const { form, repick } = appendAndLog(s, tap.kind, tap.id, tap.text, at);
    const t1 = Date.now();
    const strip = PIP().funnel.stripCandidates(
      s.d,
      s.sentence,
      at,
      s.locale ?? "en",
      s.kids
    );
    return {
      canon: canon({ form, repick, strip }),
      appendMs: t1 - t0,
      stripMs: Date.now() - t1
    };
  }
  function loadTables(sid, kidsTable, formTable, locale = "en") {
    const s = sessions.get(sid);
    s.kids = parse(kidsTable);
    s.forms = parse(formTable);
    s.locale = locale;
  }
  function barGolden(dbId, k) {
    const d = db(dbId);
    for (const h of k.history) {
      const s = PIP().funnel.openSentence(d, h.at);
      h.items.forEach((it, i) => PIP().funnel.logSelection(
        d,
        it.kind,
        it.id,
        h.at + i,
        { sentenceId: s, position: i }
      ));
      PIP().funnel.closeSentence(d, s, h.at + h.items.length, "spoken");
    }
    const { shown, ending } = PIP().funnel.stripRanked(
      d,
      k.phrase,
      k.at,
      "en",
      parse(k.kids)
    );
    return { shown, ending };
  }
  function formGolden(dbId, k) {
    const d = db(dbId);
    const s = {
      d,
      forms: parse(k.forms),
      kids: null,
      sentence: [],
      sentenceId: null,
      pos: 0,
      locale: "en"
    };
    const t0 = k.at ?? Date.now();
    let ti = 0;
    for (const spec of k.taps) {
      const at = t0 + ti++ * 1e3;
      if (spec.entity) {
        d.prepare(
          "INSERT INTO personal_entity (id, spoken_name, status) VALUES ('ent_leo', ?, 'active')"
        ).run(spec.entity);
        if (spec.link) {
          d.prepare(
            `INSERT INTO entity_enrichment
             (id, entity_id, sense_suggestion, model, prompt_version, status)
           VALUES ('enr_link', 'ent_leo', ?, 'manual', 'v1', 'ready')`
          ).run(spec.link);
        }
        appendAndLog(s, "entity", "ent_leo", spec.entity, at);
      } else {
        appendAndLog(s, "sense", spec.sense, spec.text ?? null, at);
      }
    }
    if (k.speak && s.sentence.length) {
      const last = s.sentence[s.sentence.length - 1];
      if (last.kind === "sense" && last.id) {
        const f = PIP().forms.formFor(
          d,
          s.forms,
          s.sentence.slice(0, -1),
          last.id,
          PIP().forms.EOS,
          last.features
        );
        if (f.text !== last.text) {
          last.text = f.text;
          last.labelId = f.labelId;
          last.features = f.features;
        }
      }
    }
    let bar = null;
    if (k.barRank) {
      const { shown } = PIP().funnel.stripRanked(
        d,
        s.sentence.map((x) => ({ kind: x.kind, id: x.id })),
        k.at,
        "en",
        parse(k.kids)
      );
      bar = shown.map((c) => PIP().forms.formFor(d, s.forms, s.sentence, c.id).text ?? c.id);
    }
    return { texts: s.sentence.map((x) => x.text), last: s.sentence.at(-1)?.text, bar };
  }
  function oneEdit(dbId, call, args) {
    const fn = call.split(".").reduce((o, k) => o?.[k], PIP());
    if (typeof fn !== "function") throw new Error(`no core fn ${call}`);
    fn(db(dbId), ...args ?? []);
    return true;
  }
  return __toCommonJS(harness_exports);
})();
